### ISSUE TITLE
Not functionning!

### ISSUE THREAD

**Issue by Omegasinus** [DRM-Scripts/Movistar#2]
Hi me again  thanks again for your great job  this is repostory is not working!?

Regards

**Comment by DRM-Scripts** [comment]
What exactly isn’t working?

As the script is working minus Dazn channels which need new keys. Tested as of Friday afternoon.

**Comment by Omegasinus** [comment]
Hi thanks for the replay
cd /home  have to be    cd /home/wvtohls
git clone https://github.com/DRM-Scripts/Movistar/wvtohls
But the rerpos. is not online anymore 
so i added it manualy and i finish the instalation manualy
Regards

**Comment by DRM-Scripts** [comment]
> Hi thanks for the replay
> cd /home have to be cd /home/wvtohls
> git clone https://github.com/DRM-Scripts/Movistar/wvtohls
> But the rerpos. is not online anymore
> so i added it manualy and i finish the instalation manualy
> Regards

But your commenting on the repo so how can it not be online anymore 😂

**Comment by Omegasinus** [comment]
> > Hi thanks for the replay
> > cd /home have to be cd /home/wvtohls
> > git clone https://github.com/DRM-Scripts/Movistar/wvtohls
> > But the rerpos. is not online anymore
> > so i added it manualy and i finish the instalation manualy
> > Regards
> 
> But your commenting on the repo so how can it not be online anymore 😂
lol:)
![image](https://user-images.githubusercontent.com/127033084/223160879-4a95b3ac-79f9-4726-9c83-e5530ffff951.png)
talking about this link https://github.com/DRM-Scripts/Movistar/wvtohls    try it :)

**Comment by DRM-Scripts** [comment]
> > Hi thanks for the replay
> > cd /home have to be cd /home/wvtohls
> > git clone https://github.com/DRM-Scripts/Movistar/wvtohls
> > But the rerpos. is not online anymore
> > so i added it manualy and i finish the instalation manualy
> > Regards
> 
> But your commenting on the repo so how can it not be online anymore 😂 lol:) ![image](https://user-images.githubusercontent.com/127033084/223160879-4a95b3ac-79f9-4726-9c83-e5530ffff951.png) talking about this link https://github.com/DRM-Scripts/Movistar/wvtohls try it :)

Apologies, so repo isn’t the issue, wrong command stated should have been wget instead of got clone. Sorted

**Comment by Omegasinus** [comment]
no the repo. is not the issue ,bc i instaled manualy and working maybe i dit expline very wel  thanks

**Comment by Omegasinus** [comment]
and herer cd /home/wvtohls/scripts &&.....................
